#!/bin/sh


list="
calibTable_out_MCHighEta_AB_EEN_withEtaScale_MC_V8Elec_Mode781_Method7_AB_MC_3.dat 
calibTable_out_MCHighEta_AB_EEP_withEtaScale_MC_V8Elec_Mode781_Method7_AB_MC_3.dat 
calibTable_out_MCHighEta_C_EEN_withEtaScale_MC_V8Elec_Mode781_Method7_C_MC_3.dat 
calibTable_out_MCHighEta_C_EEP_withEtaScale_MC_V8Elec_Mode781_Method7_C_MC_3.dat 
calibTable_out_MCHighEta_D_EEN_withEtaScale_MC_V8Elec_Mode781_Method7_D_MC_3.dat 
calibTable_out_MCHighEta_D_EEP_withEtaScale_MC_V8Elec_Mode781_Method7_D_MC_3.dat 
"

for file in $list;
do
  echo "draw $file" 
  ./draw_calibTable.exe $file
done 
